# url of Meteos backend to fetch environment samples from
meteos_backend_url = "https://artin.space1/meteos/api"

# token of telegram bot that is used for subscribing to notifications and
# sending notification messages to subscribed users
tg_bot_token = "5366431629:AAEZnMxpZoRTIhSwkfBxX1fHrUJSu6ELl8s"

# how often to check environment conditions
check_interval_sec = 30

# what period to use for fetching latest environment samples from backend.
# this should be equal or longer than sampling interval, otherwise no samples may
# be received from backend, which is considered error
latest_samples_period_sec = 60

# how long to wait for successful backend response until sending error notification
backend_error_timeout_sec = 30
